### ISSUE TITLE
Upload Image & File

### ISSUE THREAD

**Issue by rei-gun** [GetStream/stream-net#26]
Where is the upload function in C#? 

https://getstream.io/docs/c_sharp/#files_upload

**Comment by Christopherjl** [comment]
Any news on this?

**Comment by ferhatelmas** [comment]
Slipped a bit, we can add this week.

**Comment by Christopherjl** [comment]
Hi ferhatelmas,

   Please grant me access so I may push my branch. I have implemented Image.Upload

Chris

**Comment by Christopherjl** [comment]
Is there any chance you could get me a -beta for this week? It would be appreciated

**Comment by ferhatelmas** [comment]
Thanks for the PR, I should be able to release it today.

**Comment by Christopherjl** [comment]
Thanks so much!!

**Comment by Christopherjl** [comment]
I still dont see it in nuget. Did you release?

**Comment by Christopherjl** [comment]
I seen that you merged my Pull request. Thanks, Do you think you could get me a '-beta' deployment on nuget?

**Comment by svassr** [comment]
Can't wait to see that feature released. Thanks

**Comment by mxmcg** [comment]
Thank you @Christopherjl for adding this feature

**Comment by patromain** [comment]
I need this feature too thank you

**Comment by Christopherjl** [comment]
Any news on this?

**Comment by ferhatelmas** [comment]
Delayed a bit, coming today.

**Comment by Christopherjl** [comment]
Thanks for the info :-)

**Comment by Christopherjl** [comment]
Do you think it will be out today?

**Comment by ferhatelmas** [comment]
Released as 4.1.1. Thanks for your patience and collaboration.
