### ISSUE TITLE
"signature is invalid" when using CreateUserSessionToken

### ISSUE THREAD

**Issue by ibebbs** [GetStream/stream-net#38]
Hi,

I'm using version 3.0.1 of the ['stream-net' package](https://www.nuget.org/packages/stream-net/) and hitting a "signature is invalid" exception when trying to retrieve a feed using a user session token. I've seen lots of people encounter this issue in lots of language SDKs but the reported issues are either [unanswered](https://github.com/GetStream/feeds-sample-android/issues/1) or [closed without explanation](https://github.com/GetStream/stream-go2/issues/86). Perhaps there's an issue that has been addressed in other SDK's but not in the 'stream-net' package?

Anyway, here is a simple reproduction:

```c#
// Executed on the server
var serverConnection = new StreamClient(apiKey, apiSecret);
var clientToken = serverConnection.CreateUserSessionToken(userId);

// Just to verify that the 'server' can retrieve the users feed
var serverResponse = await serverConnection.Feed("users", userId).GetActivities(); // executes correctly
display($"Activites retrieved on server: {serverResponse.Count()}"); // Expect 0

// Executed on the client
var clientConnection = new StreamClient(apiKey, clientToken);
var clientResponse = await clientConnection.Feed("users", userId).GetActivities(); // fails with "signature is invalid"
display($"Activites retrieved on client: {clientResponse.Count()}");
```
Which results in this output:
```
Activites retrieved on server: 0
Error: Stream.StreamException: signature is invalid
at Stream.StreamException.FromResponse(RestResponse response)
at Stream.StreamFeed.GetActivities(Int32 offset, Int32 limit, FeedFilter filter, ActivityMarker marker)
at Submission#16.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

The code _seems_ to be correct according to the [documentation](https://getstream.io/activity-feeds/docs/dotnet-csharp/auth_and_permissions/?language=cs) so any suggestions on how to resolve this issue?

Thanks in advance.

gz#9002

**Comment by shodgetts** [comment]
Agent comment from Seetha in <a href='https://getstream.zendesk.com/agent/tickets/9002'>Zendesk ticket #9002</a>:<br><br>Hi

Thanks for reaching out to us.
"signature is invalid" error usually means your token is generated using an invalid signature. Possible that there is a mismatch between the API-key and the secret or a different secret has been used.
Can you please email support@getsream.io with your API-Key and the token generated and we can validate it for you.

Cheers
Seetha

**Comment by ferhatelmas** [comment]
```c#
// Executed on the client
var clientConnection = new StreamClient(apiKey, clientToken);
var clientResponse = await clientConnection.Feed("users", userId).GetActivities(); // fails with "signature is invalid"
display($"Activites retrieved on client: {clientResponse.Count()}");
```

This part is wrong because C# client is a pure backend client and expects a secret. It can generate client tokens by being backend client but you can't use to create a new client. You need to pass it to a client SDK such as JS.
