### ISSUE TITLE
Allow C# client to connect with a session token

### ISSUE THREAD

**Issue by ibebbs** [GetStream/stream-net#39]
According to [this issue](https://github.com/GetStream/stream-net/issues/38) the C# client cannot connect using a session token. Unfortunately we are looking to write a native client app based on C# (Xamarin/Uno) and not being able to use the C# SDK in this way is a major impediment.

Is there any reason the C# client cannot be extended to use a session token? If it is just a case of requiring the appropriate code to be implemented, I'd be happy to port the JS to C# and provide a PR.

Thanks

gz#9144

**Comment by ferhatelmas** [comment]
It's foreseen and assumed to be used for backend. It can be extended though. Feel free to submit a PR or let us know so that we can make the change.

**Comment by ibebbs** [comment]
Thanks, it was pretty easy to do. I've submitted a PR.
