### ISSUE TITLE
StreamChatException.FromResponse crashes in case of Http timeout

### ISSUE THREAD

**Issue by cliffofdeath** [GetStream/stream-net#44]
When StreamChatException.FromResponse() is called in case of a Http timeout, JsonConvert.DeserializeObject<StreamChatException.ExceptionState>(response.Content) causes a Newtonsoft.Json.JsonReaderException. 
The content of response.Content is in that case "Request Timeout".

gz#9477

**Comment by shodgetts** [comment]
Agent comment from Anders Lund in <a href='https://getstream.zendesk.com/agent/tickets/9477'>Zendesk ticket #9477</a>:<br><br>Hi there,

We'll take a look into this as soon as we can.

**Comment by peterdeme** [comment]
https://github.com/GetStream/stream-net/pull/80
