### ISSUE TITLE
Public Activity ID setter

### ISSUE THREAD

**Issue by weslenng** [GetStream/stream-net#54]
I think the activity ID setter should be public [https://github.com/GetStream/stream-net/blob/master/src/stream-net/Activity.cs#L29](https://github.com/GetStream/stream-net/blob/master/src/stream-net/Activity.cs#L29)

It's pretty useful when you're constructing a `Activity` from scratch to put in `UpdateActivity`

gz#13650

**Comment by shodgetts** [comment]
Agent comment from Cody Smith in <a href='https://getstream.zendesk.com/agent/tickets/13650'>Zendesk ticket #13650</a>:<br><br>Hey there,
Thank you for your feedback. I'll forward this along to our product team for their consideration.

I'll mark this as tentatively resolved but feel free to respond if you have any further questions.

All the best,
Cody
<br><p><em><small>°°°</small></em></p>
