### ISSUE TITLE
Serializing object properties to camelcase in SetData

### ISSUE THREAD

**Issue by chmchmchm** [GetStream/stream-net#62]
We're calling [Activity.SetData](https://github.com/GetStream/stream-net/blob/6c740e1881556d5080240878d776143b626942fe/src/stream-net/Activity.cs#L86-L89) where `data` is an instance of a class with Pascal case property names, but we'd prefer the properties to appear in Stream as camel case. Do you have any advice for this, e.g. does the client support us converting Pascal case property names to camel case? Or would you consider making a change to add that?

I'd also be happy to try a PR if you'd prefer - my guess is that `SetData` could take an optional `JsonSerializer` parameter that we could set up with a `CamelCasePropertyNamesContractResolver`, and then `SetData` passes that serializer to `FromObject`.

Either way thanks for the client, it's been great to use so far.

**Comment by peterdeme** [comment]
@chmchmchm would that work for you? https://github.com/GetStream/stream-net/pull/63

**Comment by chmchmchm** [comment]
@peterdeme yeah that's perfect, thanks!

**Comment by peterdeme** [comment]
https://github.com/GetStream/stream-net/releases/tag/4.7.0
