### ISSUE TITLE
Setting collection data to an object

### ISSUE THREAD

**Issue by chmchmchm** [GetStream/stream-net#66]
Hiya, we're using [GenericData.SetData](https://github.com/GetStream/stream-net/blob/6c740e1881556d5080240878d776143b626942fe/src/stream-net/GenericData.cs#L21) in both this client and the javascript client. In the javascript client, the docs example allows for passing in an object with multiple properties to be serialized.

In this client I can't see a way to do that except setting multiple name/value pairs? Is there a way to pass in an object instead? If not, would you be able to add an overload for that?

Thanks very much!

-------

In the Stream docs on collections [here](https://getstream.io/activity-feeds/docs/dotnet-csharp/collections_introduction/?language=javascript#parameters):

1. The javascript docs passing in an object with two properties
![image](https://user-images.githubusercontent.com/87622820/153964833-d5610816-df48-4e60-8927-1ca25a1197a9.png)

2. The C# docs calling `SetData` once for each property
![image](https://user-images.githubusercontent.com/87622820/153964981-0e25b853-13aa-44f0-ac3d-1e6d422bd58b.png)

3. What we'd be keen for
```
var collectionData = new GenericData();
collectionData.SetData(new Food("cheese burger", "4 stars"));
await client.Collections.Add("food", collectionData, "cheese-burger");
```

**Comment by peterdeme** [comment]
Hey @chmchmchm!

So it's important to know that the properties of collection entries are key-value pairs. `new Food("cheese burger", "4 stars")` is a good value, but it needs to have a key.

But you could do this already:
```csharp
collectionData.SetData(foodId, new Food("cheese burger", "4 stars"));
```

Would that work for you?

**Comment by chmchmchm** [comment]
I think if we did that the collection would have the structure

```
{
  "foodIdValue": {
    "name": "cheese burger",
    "rating": "4 stars"
  }
}
```

but we want this structure, without the extra level of nesting:

```
{
  "name": "cheese burger",
  "rating": "4 stars"
}
```

Is there any way to get that without calling SetData once for `name` and then again for `rating`?

**Comment by peterdeme** [comment]
Hey @chmchmchm,

The code snippet I have provided to you does exactly that.

```csharp
var foodId = "foodIdValue";
collectionData.SetData(foodId, new Food("cheese burger", "4 stars"));
```

This will do that:
```json
{
  "foodIdValue": {
    "name": "cheese burger",
    "rating": "4 stars"
  }
}
```

**Comment by chmchmchm** [comment]
Hi @peterdeme,

Thanks for looking into this but I think we're misunderstanding each other - what you posted here:

![image](https://user-images.githubusercontent.com/87622820/154365119-83687713-3978-4d1c-8c7c-6556fdbd1fdd.png)

That is the structure we _don't_ want, from my message here:

![image](https://user-images.githubusercontent.com/87622820/154365229-dd755ba1-f1c4-42fd-b397-3bdcf0174fb9.png)

What we would like is to not have `foodIdValue`, is that possible? To _only_ have name and rating:

```
{
  "name": "cheese burger",
  "rating": "4 stars"
}
```

We'd like to be able to get that format by running just one command, passing the whole object, the same as you can do with the javascript client.

**Comment by chmchmchm** [comment]
Hey @peterdeme - if that last reply isn't making sense, I'd be happy to set up a call to chat about it if that could be easier!

**Comment by ferhatelmas** [comment]
@chmchmchm it makes sense. Peter is back on Wed and we can probably provider an override

**Comment by peterdeme** [comment]
@chmchmchm hopefully this solves your problem: https://github.com/GetStream/stream-net/pull/68/

**Comment by chmchmchm** [comment]
Hi, sorry for the slow reply.

I'm not sure that that does solve our problem, are you saying we should use the `SetData<T>(string name, T data, JsonSerializer serializer)`  overload? Doesn't that still require a `name` property, where `name` would be a key to the rest of the data? We want just the object properties as the data themselves, with no other name.

Like this format:

```
{
  "1": "2",
  "3": "4"
}
```

How could we use that overload to get this format?

**Comment by peterdeme** [comment]
@chmchmchm 

look at this one:
https://github.com/GetStream/stream-net/pull/68/files#diff-532c5c20bf6b7da511a82eab7e025dd7d47b940f0caba28d6a713a12ab7ac01cR1578

**Comment by chmchmchm** [comment]
This is addressed by upgrading to v6 of the library, thanks very much everyone for the update 👍
